In [ ]:
import pandas as pd

ruta = "/content/drive/MyDrive/datos DEIS/mortalidad_2005_2023_analitico.parquet"
df = pd.read_parquet(ruta)

In [ ]:
df.shape

(922900, 18)

In [ ]:
list(df.columns)

['PROVRES',
 'SEXO',
 'CAUSA',
 'MAT',
 'GRUPEDAD',
 'CUENTA',
 'anio',
 'source_file',
 'PROVRES_norm',
 'codigo',
 'provincia',
 'SEXO_norm',
 'codigo_sexo',
 'sexo_desc',
 'MAT_desc',
 'CAUSA_norm',
 'codigo_causa',
 'causa_desc']

In [ ]:
df.dtypes

PROVRES         object
SEXO            object
CAUSA           object
MAT             object
GRUPEDAD        object
CUENTA          object
anio            object
source_file     object
PROVRES_norm    object
codigo          object
provincia       object
SEXO_norm       object
codigo_sexo     object
sexo_desc       object
MAT_desc        object
CAUSA_norm      object
codigo_causa    object
causa_desc      object
dtype: object

In [ ]:
df.head(3)

,PROVRES,SEXO,CAUSA,MAT,GRUPEDAD,CUENTA,anio,source_file,PROVRES_norm,codigo,provincia,SEXO_norm,codigo_sexo,sexo_desc,MAT_desc,CAUSA_norm,codigo_causa,causa_desc
0,50,2,R99,,11_50 a 54,10,2005,Mortalidad año 2005.xlsx,50,50,Mendoza,2,2,Mujer,No es muerte materna,R99,R99,Otras causas mal definidas y las no especifica...
1,14,1,F10,,12_55 a 59,1,2005,Mortalidad año 2005.xlsx,14,14,Córdoba,1,1,Varón,No es muerte materna,F10,F10,Trastornos mentales y del comportamiento debid...
2,62,1,N05,,17_80 y más,1,2005,Mortalidad año 2005.xlsx,62,62,Río Negro,1,1,Varón,No es muerte materna,N05,N05,Síndrome nefrítico no especificado

In [ ]:
# Conversión segura
df["CUENTA"] = pd.to_numeric(df["CUENTA"], errors="coerce")
df["anio"] = pd.to_numeric(df["anio"], errors="coerce")

In [ ]:
df[["CUENTA", "anio"]].dtypes

CUENTA    int64
anio      int64
dtype: object

In [ ]:
df[["CUENTA", "anio"]].isna().sum()

CUENTA    0
anio      0
dtype: int64

In [ ]:
df["anio"].min(), df["anio"].max()

(2005, 2023)

In [ ]:
df["provincia"].nunique()

26

In [ ]:
sorted(df["provincia"].unique())

['Buenos Aires',
 'Catamarca',
 'Chaco',
 'Chubut',
 'Ciudad Aut. de Buenos Aires',
 'Corrientes',
 'Córdoba',
 'Entre Ríos',
 'Formosa',
 'Jujuy',
 'La Pampa',
 'La Rioja',
 'Lugar no especificado',
 'Mendoza',
 'Misiones',
 'Neuquén',
 'Otro país',
 'Río Negro',
 'Salta',
 'San Juan',
 'San Luis',
 'Santa Cruz',
 'Santa Fe',
 'Santiago del Estero',
 'Tierra del Fuego',
 'Tucumán']

In [ ]:
df["CAUSA_norm"].nunique()

1504

In [ ]:
df[df["causa_desc"] == "No mapeado (fuera de diccionario CODMUER)"].shape

(35, 18)

In [ ]:
df["CUENTA"].describe()

count    922900.000000
mean          6.921104
std          52.953199
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max        7372.000000
Name: CUENTA, dtype: float64

In [ ]:
df["CUENTA"].sum()

np.int64(6387487)

In [ ]:
# Verificación de integridad y estructura de variables normalizadas
info_basica = {
    "Total Registros": len(df),
    "Columnas": df.columns.tolist(),
    "Muestreo MAT_desc": df['MAT_desc'].unique().tolist(),
    "Conteo COVID (U07)": len(df[df['CAUSA_norm'] == 'COVID-19']) if 'CAUSA_norm' in df.columns else "Columna no hallada"
}

# Verificación de Nulos en variables críticas
nulos = df[['PROVRES_norm', 'SEXO_norm', 'CAUSA_norm', 'MAT_desc']].isnull().sum()

print("--- REPORTE DE ESTRUCTURA DEIS ---")
for k, v in info_basica.items():
    print(f"{k}: {v}")
print("\n--- VALORES NULOS EN VARIABLES NORMALIZADAS ---")
print(nulos)

--- REPORTE DE ESTRUCTURA DEIS ---
Total Registros: 922900
Columnas: ['PROVRES', 'SEXO', 'CAUSA', 'MAT', 'GRUPEDAD', 'CUENTA', 'anio', 'source_file', 'PROVRES_norm', 'codigo', 'provincia', 'SEXO_norm', 'codigo_sexo', 'sexo_desc', 'MAT_desc', 'CAUSA_norm', 'codigo_causa', 'causa_desc']
Muestreo MAT_desc: ['No es muerte materna', 'Muerte materna', 'Muerte materna tardía', 'Secuela de causa obstétrica']
Conteo COVID (U07): 0

--- VALORES NULOS EN VARIABLES NORMALIZADAS ---
PROVRES_norm    0
SEXO_norm       0
CAUSA_norm      0
MAT_desc        0
dtype: int64

In [ ]:
# Validación de códigos U07 y mapeo de CAUSA_norm
check_covid = df[df['codigo_causa'].str.contains('U07', na=False, case=False)]

print("--- DIAGNÓSTICO DE MAPEADO COVID (U07) ---")
print(f"Registros con código U07 en 'codigo_causa': {len(check_covid)}")
if len(check_covid) > 0:
    print("Muestra de CAUSA_norm para estos registros:")
    print(check_covid['CAUSA_norm'].unique())

# Verificación de consistencia en nombres de causas
print("\n--- TOP 5 CAUSAS EN CAUSA_norm ---")
print(df['CAUSA_norm'].value_counts().head(5))

--- DIAGNÓSTICO DE MAPEADO COVID (U07) ---
Registros con código U07 en 'codigo_causa': 2424
Muestra de CAUSA_norm para estos registros:
['U07']

--- TOP 5 CAUSAS EN CAUSA_norm ---
CAUSA_norm
J18    12637
R99    11327
A41    10350
I21     9790
I50     9319
Name: count, dtype: int64

In [ ]:
# Aplicación de Regla 1.c: Mapeo de COVID-19
df['CAUSA_norm'] = df['codigo_causa'].apply(lambda x: 'COVID-19' if 'U07' in str(x) else x)

# Verificación de la corrección
print("--- VERIFICACIÓN POST-MAPEO ---")
print(f"Registros identificados como 'COVID-19': {len(df[df['CAUSA_norm'] == 'COVID-19'])}")

# Control de integridad: ¿Perdimos registros?
if len(df) == 922900:
    print("Integridad de registros: OK (922.900)")
else:
    print(f"ALERTA: Cantidad de registros alterada: {len(df)}")

--- VERIFICACIÓN POST-MAPEO ---
Registros identificados como 'COVID-19': 2424
Integridad de registros: OK (922.900)

In [ ]:
# Contar registros por año
conteo_por_anio = df['anio'].value_counts().sort_index()

print("--- REGISTROS POR AÑO ---")
print(conteo_por_anio)

--- REGISTROS POR AÑO ---
anio
2005    45567
2006    45650
2007    47060
2008    46980
2009    47613
2010    47735
2011    47110
2012    47382
2013    48471
2014    48346
2015    52511
2016    51177
2017    49831
2018    49831
2019    49820
2020    48817
2021    49665
2022    50188
2023    49146
Name: count, dtype: int64

Observaciones sobre el Volumen Anual:

+ Estabilidad General: Vemos una serie muy estable, oscilando mayormente entre los 45.000 y 52.000 registros anuales. Esto es una excelente señal de consistencia en la carga de datos (Regla 1.a).

+ El Salto de 2015: Notarás que en 2015 hay un incremento a 52.511, el punto más alto de la serie.

+ Periodo 2020-2023: A diferencia de lo que uno podría esperar por la pandemia, los registros totales se mantienen en el rango de los 48.000-50.000. Esto sugiere que no estamos viendo una "explosión" de muertes totales en estos datos específicos, sino una redistribución de causas.

In [ ]:
# Conteo de registros por sexo normalizado
distribucion_sexo = df['SEXO_norm'].value_counts()

# Cálculo del porcentaje
porcentaje_sexo = (df['SEXO_norm'].value_counts(normalize=True) * 100).round(2)

print("--- DISTRIBUCIÓN POR SEXO (SEXO_norm) ---")
print(distribucion_sexo)
print("\n--- PORCENTAJE (%) ---")
print(porcentaje_sexo)

--- DISTRIBUCIÓN POR SEXO (SEXO_norm) ---
SEXO_norm
1    503497
2    413619
9      5784
Name: count, dtype: int64

--- PORCENTAJE (%) ---
SEXO_norm
1    54.56
2    44.82
9     0.63
Name: proportion, dtype: float64

Lectura de los Resultados:

+ Categoría 1 (Varones): Representan el 54,56% (503.497 registros). Es la mayoría del dataset.

+ Categoría 2 (Mujeres): Representan el 44,82% (413.619 registros).

+ Categoría 9 (Indeterminado/No especificado): Representan solo el 0,63% (5.784 registros).

In [ ]:
# Conteo de registros por provincia normalizada (PROVRES_norm)
distribucion_provincia = df['PROVRES_norm'].value_counts()

# Cálculo del porcentaje acumulado
porcentaje_provincia = (df['PROVRES_norm'].value_counts(normalize=True) * 100).round(2)

# Unimos ambos en un pequeño resumen
resumen_geografico = pd.DataFrame({
    'Registros': distribucion_provincia,
    'Porcentaje (%)': porcentaje_provincia
})

print("--- DISTRIBUCIÓN POR JURISDICCIÓN (PROVRES_norm) ---")
print(resumen_geografico)

--- DISTRIBUCIÓN POR JURISDICCIÓN (PROVRES_norm) ---
              Registros  Porcentaje (%)
PROVRES_norm
06               130710           14.16
82                73619            7.98
14                66217            7.17
02                60003            6.50
50                49960            5.41
30                41802            4.53
90                41368            4.48
22                41130            4.46
66                39410            4.27
18                36817            3.99
86                32594            3.53
54                32190            3.49
70                30273            3.28
62                29526            3.20
38                28245            3.06
34                26504            2.87
58                24963            2.70
26                23325            2.53
74                21918            2.37
10                19085            2.07
42                17963            1.95
46                17041            1.85
78                14737            1.60
99                10499            1.14
94                 7568            0.82
98                 5433            0.59

Lectura de los Resultados Geográficos:

+ Jurisdicciones Mayores:

06 (Buenos Aires): 14,16% (La de mayor volumen, como es esperado).

82 (Santa Fe): 7,98%.

14 (Córdoba): 7,17%.

02 (CABA): 6,50%.

+ Calidad del Dato: Las categorías 99 y 98 (generalmente referidas a "Sin información" o "Localidad no especificada") suman apenas un 1,73%. Esto refuerza la idea de que el dataset tiene una cobertura geográfica muy sólida para el análisis provincial.

In [ ]:
# Ranking de las 10 causas principales
top_10_causas = df['CAUSA_norm'].value_counts().head(10)

# Para entender mejor qué son esos códigos, traemos una muestra de la descripción
# Creamos un diccionario de referencia rápido código -> descripción
mapeo_nombres = df.groupby('CAUSA_norm')['causa_desc'].first()
top_10_con_nombre = pd.DataFrame({
    'Registros': top_10_causas,
    'Descripción': top_10_causas.index.map(mapeo_nombres)
})

print("--- TOP 10 CAUSAS DE MUERTE (2005-2023) ---")
print(top_10_con_nombre)

--- TOP 10 CAUSAS DE MUERTE (2005-2023) ---
            Registros                                        Descripción
CAUSA_norm
J18             12637                 Neumonía organismo no especificado
R99             11327  Otras causas mal definidas y las no especifica...
A41             10350                                       Otras Sepsis
I21              9790                        Infarto agudo del miocardio
I50              9319                             Insuficiencia cardíaca
I61              9124                         Hemorragia intraencefálica
X70              8872  Lesión autoinfligida intencionalmente por ahor...
E14              8793                  Diabetes mellitus no especificada
C34              8699        Tumor maligno de los bronquios y del pulmón
C18              8562                            Tumor maligno del colon

In [ ]:
# Verificación del significado de 'CUENTA'
print(f"Total de filas (registros): {len(df)}")
print(f"Suma total de la columna 'CUENTA': {df['CUENTA'].sum()}")
print("\n--- ESTADÍSTICA DE LA COLUMNA CUENTA ---")
print(df['CUENTA'].describe())

Total de filas (registros): 922900
Suma total de la columna 'CUENTA': 6387487

--- ESTADÍSTICA DE LA COLUMNA CUENTA ---
count    922900.000000
mean          6.921104
std          52.953199
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max        7372.000000
Name: CUENTA, dtype: float64

In [ ]:
# Ver todas las categorías de edad únicas y su frecuencia (ponderada por CUENTA)
distribucion_edad = df.groupby('GRUPEDAD')['CUENTA'].sum().reset_index()

print("--- RELEVAMIENTO DE GRUPOS ETARIOS ---")
print(distribucion_edad)

--- RELEVAMIENTO DE GRUPOS ETARIOS ---
              GRUPEDAD   CUENTA
0    01_Menor de 1 año   138106
1             02_1 a 9    37796
2           03_10 a 14    17135
3           04_15 a 19    47674
4           05_20 a 24    63309
5           06_25 a 29    64578
6           07_30 a 34    69945
7           08_35 a 39    84152
8           09_40 a 44   111034
9           10_45 a 49   154017
10          11_50 a 54   224833
11          12_55 a 59   324593
12          13_60 a 64   448582
13          14_65 a 69   575928
14          15_70 a 74   693955
15          16_75 a 79   810544
16         17_80 y más  2496827
17  99_Sin especificar    24479

In [ ]:
# Creamos una copia para trabajar seguros
# Separamos el código numérico del texto
df[['EDAD_orden', 'EDAD_norm']] = df['GRUPEDAD'].str.split('_', n=1, expand=True)

# Convertimos el orden a número para que 02 venga después de 01 correctamente
df['EDAD_orden'] = pd.to_numeric(df['EDAD_orden'], errors='coerce')

# Verificamos cómo quedó el mapeo
print("--- MUESTRA DE LA NUEVA ESTRUCTURA DE EDAD ---")
print(df[['GRUPEDAD', 'EDAD_orden', 'EDAD_norm']].drop_duplicates().sort_values('EDAD_orden'))

--- MUESTRA DE LA NUEVA ESTRUCTURA DE EDAD ---
               GRUPEDAD  EDAD_orden        EDAD_norm
11    01_Menor de 1 año           1   Menor de 1 año
40             02_1 a 9           2            1 a 9
234          03_10 a 14           3          10 a 14
14           04_15 a 19           4          15 a 19
31           05_20 a 24           5          20 a 24
45           06_25 a 29           6          25 a 29
21           07_30 a 34           7          30 a 34
29           08_35 a 39           8          35 a 39
37           09_40 a 44           9          40 a 44
15           10_45 a 49          10          45 a 49
0            11_50 a 54          11          50 a 54
1            12_55 a 59          12          55 a 59
4            13_60 a 64          13          60 a 64
19           14_65 a 69          14          65 a 69
5            15_70 a 74          15          70 a 74
12           16_75 a 79          16          75 a 79
2           17_80 y más          17         80 y más
93   99_Sin especificar          99  Sin especificar

La variable original GRUPEDAD presentaba una estructura compuesta (prefijo numérico + descripción), por ejemplo: 01_Menor de 1 año. Si bien los prefijos garantizan el orden, dificultan la legibilidad en reportes finales y el filtrado por rangos numéricos.

+ Acción Realizada:
Se aplicó una normalización no destructiva mediante la técnica de expansión de strings (split).

+ Resultado Estructural:

EDAD_orden: Columna de tipo numérico extraída del prefijo. Garantiza que el ordenamiento sea cronológico (ej: que el grupo "3" venga después del "2" y antes del "10").

EDAD_norm: Columna de tipo texto con la descripción limpia. Destinada a etiquetas en gráficos y tablas para una presentación académica (ej: "Menor de 1 año").

+ Justificación Metodológica:
Se mantuvo la columna original GRUPEDAD intacta para asegurar la integridad del crudo. Las nuevas columnas son derivadas y facilitan el análisis sin perder la trazabilidad de la fuente original.

Validación de consistencia estructural: Se confirma que la transformación no generó pérdida de datos (0% de nulos en las nuevas columnas) y que el mapeo es consistente para los 18 grupos identificados, incluyendo la categoría 99 (Sin especificar).

In [ ]:
# Cálculo de la mortalidad real anual (Suma de la variable CUENTA)
mortalidad_anual_real = df.groupby('anio')['CUENTA'].sum().reset_index()

# Formateo para lectura clara
mortalidad_anual_real.columns = ['Año', 'Total de Defunciones']

print("--- REPORTE DE MORTALIDAD REAL POR AÑO ---")
print(mortalidad_anual_real.to_string(index=False))

# Verificación de la Gran Suma Total
print(f"\nSuma acumulada total (2005-2023): {mortalidad_anual_real['Total de Defunciones'].sum():,}")

--- REPORTE DE MORTALIDAD REAL POR AÑO ---
 Año  Total de Defunciones
2005                293529
2006                292313
2007                315852
2008                302133
2009                304525
2010                318602
2011                319059
2012                319539
2013                326197
2014                325539
2015                333407
2016                352992
2017                341688
2018                336823
2019                341728
2020                376219
2021                436799
2022                397115
2023                353428

Suma acumulada total (2005-2023): 6,387,487

Análisis de la Serie Temporal Real:  

+ Estabilidad Pre-Pandemia: Entre 2005 y 2019, la mortalidad creció de forma inercial, pasando de ~$293.000$ a ~$341.000$ defunciones anuales, lo cual es consistente con el crecimiento y envejecimiento poblacional.

+ El Impacto de la Pandemia (2020-2021):
  - En 2020, las defunciones saltan a $376.219$.
  
  - En 2021, llegamos al pico histórico de la serie con $436.799$ defunciones. Este incremento de casi $100.000$ muertes respecto al promedio histórico es un indicador directo del exceso de mortalidad por COVID-19 y otras causas asociadas.
  
+ Normalización Post-Pandemia: En 2023 vemos un retorno hacia los niveles de 2016 ($353.428$), sugiriendo un cierre del ciclo de exceso de mortalidad pandémica.

In [ ]:
# Re-calculando el Top 10 de causas reales (Ponderadas por CUENTA)
top_10_causas_reales = df.groupby('CAUSA_norm')['CUENTA'].sum().nlargest(10).reset_index()

# Traemos la descripción para que sea legible
mapeo_nombres = df.groupby('CAUSA_norm')['causa_desc'].first()
top_10_causas_reales['Descripción'] = top_10_causas_reales['CAUSA_norm'].map(mapeo_nombres)

print("--- TOP 10 CAUSAS REALES DE MUERTE (Ponderado por CUENTA) ---")
print(top_10_causas_reales[['CAUSA_norm', 'CUENTA', 'Descripción']])

--- TOP 10 CAUSAS REALES DE MUERTE (Ponderado por CUENTA) ---
  CAUSA_norm  CUENTA                                        Descripción
0        I50  533563                             Insuficiencia cardíaca
1        J18  456390                 Neumonía organismo no especificado
2        I21  315470                        Infarto agudo del miocardio
3        R99  302421  Otras causas mal definidas y las no especifica...
4        J96  215927  Insuficiencia respiratoria no clasificada en o...
5        A41  211159                                       Otras Sepsis
6        C34  171906        Tumor maligno de los bronquios y del pulmón
7   COVID-19  163995                                           COVID-19
8        I64  162801  Accidente vascular encefálico agudo no especif...
9        E14  125209                  Diabetes mellitus no especificada

Observaciones de DEIS sobre el Top 10 Real:

+ Predominio Cardiovascular y Respiratorio: La Insuficiencia cardíaca (I50) y la Neumonía (J18) lideran con más de 450.000 defunciones cada una. Esto es consistente con los perfiles de mortalidad de países con transiciones demográficas avanzadas.

+ El lugar real del COVID-19: Ahora vemos la magnitud del impacto: 163.995 personas. Al principio solo veíamos 2.424 registros (filas), pero la ponderación nos devuelve la cifra real, que es coherente con las estadísticas oficiales de la pandemia en Argentina.

+ Alerta de Calidad (R99): La categoría "Otras causas mal definidas" (R99) ocupa el 4.º lugar con 302.421 defunciones. Como expertos en estadística vital, esto nos indica que hay un volumen importante de certificados de defunción con información incompleta, lo que suele ser un desafío para la asignación precisa de políticas de salud.

In [ ]:
# Distribución por Sexo Ponderada (Suma de CUENTA)
sexo_real = df.groupby('SEXO_norm')['CUENTA'].sum().reset_index()
sexo_real['Porcentaje (%)'] = (sexo_real['CUENTA'] / sexo_real['CUENTA'].sum() * 100).round(2)

print("--- DISTRIBUCIÓN POR SEXO REAL (Ponderado por CUENTA) ---")
print(sexo_real)

--- DISTRIBUCIÓN POR SEXO REAL (Ponderado por CUENTA) ---
  SEXO_norm   CUENTA  Porcentaje (%)
0         1  3306142           51.76
1         2  3069226           48.05
2         9    12119            0.19

In [ ]:
# Filtramos para ver solo las filas que SON muerte materna y ver qué sexo tienen asignado
check_consistencia = df[df['MAT_desc'] != 'No es muerte materna'].groupby(['MAT_desc', 'SEXO_norm'])['CUENTA'].sum().reset_index()

print("--- DISTRIBUCIÓN DE MORTALIDAD MATERNA ---")
print(maternal_dist.sort_values(by='CUENTA', ascending=False).to_string(index=False))

print("\n--- CONTROL DE CONSISTENCIA (MUERTE MATERNA vs SEXO) ---")
print(check_consistencia.to_string(index=False))

--- DISTRIBUCIÓN DE MORTALIDAD MATERNA ---
                   MAT_desc  CUENTA  Porcentaje (%)
       No es muerte materna 6381643         99.9085
             Muerte materna    5171          0.0810
      Muerte materna tardía     670          0.0105
Secuela de causa obstétrica       3          0.0000

--- CONTROL DE CONSISTENCIA (MUERTE MATERNA vs SEXO) ---
                   MAT_desc SEXO_norm  CUENTA
             Muerte materna         2    5171
      Muerte materna tardía         2     670
Secuela de causa obstétrica         2       3

In [ ]:
# Guardar el dataset con las normalizaciones aplicadas
# Esto incluye: CAUSA_norm corregida, EDAD_norm y EDAD_orden
df.to_parquet('mortalidad_validado.parquet', index=False)

print("Dataset exportado con éxito como 'mortalidad_validado.parquet'")

Dataset exportado con éxito como 'mortalidad_validado.parquet'

In [ ]:
import os
from google.colab import files
# 1. Exportar el archivo
nombre_archivo = 'mortalidad_validado.parquet'
df.to_parquet(nombre_archivo, index=False)

# 2. Forzar el refresco del sistema de archivos
os.sync()

# 3. Verificar si el archivo existe físicamente
if os.path.exists(nombre_archivo):
    print(f"✅ ¡Éxito! El archivo '{nombre_archivo}' se creó correctamente.")
    print("Iniciando descarga automática...")
    files.download(nombre_archivo) # Esto abrirá la ventana de guardado en tu PC
else:
    print("❌ Error: El archivo no se encontró. Reintenta ejecutar la celda.")

✅ ¡Éxito! El archivo 'mortalidad_validado.parquet' se creó correctamente.
Iniciando descarga automática...